name: intalim
description: InTalim Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.2
  flutter_svg: ^2.0.7
  go_router: ^13.0.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  meta: ^1.9.0
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  freezed_annotation: ^2.4.1
  marquee: ^2.0.2
  flutter_html: ^3.0.0-beta.2
  video_thumbnail: ^0.5.3
  flutter_cache_manager: ^3.3.1
  video_player: ^2.8.1
  cached_network_image: ^3.3.1
  objectbox: ^2.4.0
  objectbox_flutter_libs: ^2.4.0
  path_provider: ^2.1.1
  connectivity: ^3.0.6

dev_dependencies:
  build_runner: ^2.4.7
  objectbox_generator: any
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_logo.png'
  min_sdk_android: 21

  adaptive_icon_background: #ffffff
  adaptive_icon_foreground: #ffffff
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/person.png
    - assets/lang/
    - assets/bottom_navigation/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 400  # FontWeight.w400 is used for bold
        - asset: assets/fonts/montserrat_bold.ttf
          weight: 700  # FontWeight.w700 is used for bold
        - asset: assets/fonts/montserrat_semi_bold.ttf
          weight: 600  # FontWeight.w600 is used for semi-bold
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 500  # FontWeight.w500 is used for medium
        - asset: assets/fonts/montserrat_extra_bold.ttf
          weight: 800  # FontWeight.w800 is used for extra-bold

